### ISSUE TITLE
meet error when run script

### ISSUE THREAD

**Issue by airingursb** [denoland/webgpu-examples#12]
```
error: Uncaught (in promise) TypeError: Failed to execute 'createComputePipeline' on 'GPUDevice': 'layout' of 'GPUComputePipelineDescriptor' (Argument 1) is not of type GPUPipelineLayout.
const computePipeline = device.createComputePipeline({
                               ^
    at makeException (deno:ext/webidl/00_webidl.js:80:12)
    at deno:ext/webidl/00_webidl.js:867:15
    at Array.GPUComputePipelineDescriptor (deno:ext/webidl/00_webidl.js:712:34)
    at GPUDevice.createComputePipeline (deno:ext/webgpu/01_webgpu.js:1150:38)
    at file:///Users/airing/Files/code/wgpu-deno-example/hello-compute/mod.ts:80:32
```

deno version:
```
deno 1.23.2 (release, x86_64-apple-darwin)
v8 10.4.132.8
typescript 4.7.2
```

**Comment by crowlKats** [comment]
This has been fixed in the webgpu implementation, however deno currently doesnt have webgpu anymore; hopefully sometime soon we will be able to bring it back.

**Comment by mikejohnstn** [comment]
> deno currently doesnt have webgpu anymore

I guess that explains why this repo no longer works. :) Can you share any details about why it was removed and when it could come back?

**Comment by crowlKats** [comment]
@mikejohnstn it was removed due to performance implication on the entirety of the runtime, and given its currently extremely limited use, it was agreed that removing it was the best solution.
However, we are currently investigating bringing it back without having these performance implications

**Comment by crowlKats** [comment]
Update: WebGPU is back, and will be available in the release next Wednesday.
